name: Build Dotnet CDK
on: [pull_request]

jobs:
  build-dotnet-cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and test
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: local/dotnet-cdk:latest
          context: .
          target: build
          
