name: Release Connector Image
on:
  push:
    branches: [ main ]
    paths: 'airbyte-integrations/connectors/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
    - uses: actions/checkout@v2
      with:
        fetch-depth: '2'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Changed files
      run: |
        # test git command
        git diff --name-only HEAD HEAD~1    
    - name: Build and Test Connector
      working-directory: ./Airbyte.Cdk
      run: dotnet run publish -b
