name: Release Dotnet CDK
on:
  release:
    types: [published]

jobs:
  publish-dotnet-cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and test
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: local/dotnet-cdk:latest
          context: .
        env:
          NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
          NUGET_VERSION: ${{ github.event.release.tag_name }}